#!/usr/bin/env python3
"""Regenerate src/prometheus_cli/splash_frames.py from a base shape.

The frames represent a smooth simulated 3D Y-axis rotation of the PROMETHEUS
mark. Each frame compresses the shape horizontally by cos(theta), mirrors it on
the back half, and shades columns by a curved-surface heuristic so the mark
appears to TURN rather than slide.

The base shape below is a clearly-labeled PLACEHOLDER stand-in (a bracketed
ember). When the official company logo is supplied, replace `BASE_SHAPES` with
density grids derived from that image (threshold the alpha/luminance to a filled
grid per size) and re-run:

    python tools/generate_splash.py

This must reproduce src/prometheus_cli/splash_frames.py byte-for-byte.
"""
from __future__ import annotations

import math
from pathlib import Path

# PLACEHOLDER: temporary test shape — replace with official logo-derived art.
# Each shape is a list of equal-length strings; '#' = filled, anything else = empty.
# Shapes are left/right symmetric so the back half mirrors the front cleanly.
BASE_SHAPES: dict[str, list[str]] = {
    "compact": [
        "##############",
        "#............#",
        "#...######...#",
        "#...######...#",
        "#............#",
        "##############",
    ],
    "normal": [
        "########################",
        "#......................#",
        "#......##########......#",
        "#......##......##......#",
        "#......##......##......#",
        "#......##########......#",
        "#......................#",
        "########################",
    ],
    "wide": [
        "########################################",
        "#......................................#",
        "#............################..........#",
        "#............##..........##............#",
        "#............##..........##............#",
        "#............##..........##............#",
        "#............##..........##............#",
        "#............################..........#",
        "#......................................#",
        "########################################",
    ],
}

FRAME_COUNT = {"compact": 16, "normal": 24, "wide": 24}
SHADE_CHARS = [" ", "·", "░", "▒", "▓", "█"]
COLOR_SHADES = [" ", "·", "░", "▒", "▓", "█"]


def _filled_mask(shape: list[str]) -> list[list[bool]]:
    return [[ch == "#" for ch in row] for row in shape]


def _normalize_shape(shape: list[str]) -> list[str]:
    width = max(len(row) for row in shape)
    return [row.ljust(width) for row in shape]


def render_frame(shape: list[str], theta: float, color: bool = False) -> list[str]:
    shape = _normalize_shape(shape)
    mask = _filled_mask(shape)
    height = len(shape)
    width = len(shape[0])
    cos_t = math.cos(theta)
    abs_cos = abs(cos_t)
    out: list[str] = []
    for y in range(height):
        line_chars: list[str] = []
        for ox in range(width):
            u = (ox - width / 2 + 0.5) / (width / 2)
            if abs_cos < 1e-3:
                line_chars.append(" " if not _any_filled(mask, y) else SHADE_CHARS[2])
                continue
            x_rel = u / cos_t
            if abs(x_rel) > 1.0:
                line_chars.append(" ")
                continue
            sx = int(x_rel * (width / 2) + width / 2 - 0.5)
            sx = max(0, min(width - 1, sx))
            if cos_t < 0:
                sx = width - 1 - sx
            filled = mask[y][sx] if 0 <= y < height else False
            if not filled:
                line_chars.append(" ")
                continue
            shade = round((1.0 - x_rel * x_rel) * 3.0) + 1
            shade = max(1, min(5, shade))
            line_chars.append((COLOR_SHADES if color else SHADE_CHARS)[shade])
        out.append("".join(line_chars))
    return out


def _any_filled(mask: list[list[bool]], y: int) -> bool:
    if 0 <= y < len(mask):
        return any(mask[y])
    return False


def all_frames(size: str) -> list[list[str]]:
    shape = BASE_SHAPES[size]
    n = FRAME_COUNT[size]
    return [render_frame(shape, 2 * math.pi * i / n) for i in range(n)]


def _to_python_literal(frames_by_size: dict[str, list[list[str]]]) -> str:
    lines = [
        '"""Generated ASCII rotation frames for the PROMETHEUS splash.',
        "",
        "PLACEHOLDER: temporary test shape - replace with official logo-derived art.",
        'Generated by tools/generate_splash.py. Do not edit by hand.',
        '"""',
        "from __future__ import annotations",
        "",
        "FRAMES: dict[str, list[list[str]]] = {",
    ]
    for size in ("compact", "normal", "wide"):
        frames = frames_by_size[size]
        lines.append(f'    {size!r}: [')
        for frame in frames:
            rows = ", ".join(repr(row) for row in frame)
            lines.append(f"        [{rows}],")
        lines.append("    ],")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    repo = Path(__file__).resolve().parent.parent
    out = repo / "src" / "prometheus_cli" / "splash_frames.py"
    frames = {size: all_frames(size) for size in ("compact", "normal", "wide")}
    out.write_text(_to_python_literal(frames), encoding="utf-8")
    print(f"wrote {out} ({out.stat().st_size} bytes)")
    for size in frames:
        counts = {len(f) for f in frames[size]}
        widths = {len(row) for f in frames[size] for row in f}
        print(f"  {size}: {len(frames[size])} frames, heights={counts}, widths={widths}")


if __name__ == "__main__":
    main()
